unique_ids:
  forms: {EditableCard: ZPZ5HO7JF2HQRFKMTUZ5HMGC56GVQRKX, MessagePill: 4HMQ4AYEDJT22I2YNFTDLCQCFDA4FZ3F,
    PageBreak: WTLLV4JQCV7R3UJVOO24AD57TDWC7TCO, Demo: 7OHCYYNDEID2BZ5AN5DDP7K4XXGJTRZB,
    ProgressBar.Determinate: J7HWVD2WBMZY7OCSOPNLPLHFQ4XCJBR2, ProgressBar.Indeterminate: KSULDKU4IPBMWPU7OQLLU4YN35XCYTSV}
  modules: {messaging: 7IHICO4L27LD43V5MAW3DANJOUVGAVKQ, style: HH5PGMA7JQVLDPS5HWTF7IUGYMVKZQN5,
    popover: NBYGQSD74EAZEJRNYQY7DDV53HII25GS, session: I6CPANLB5O7M2VDR2CZKLBV7THBW2SJF,
    utils: 4RYXZHVVAM7TYK56EDOUW2KGUHQEIYU2, ProgressBar: 6RDMGEBZGTXV32KLZDKWPGBWXS3QKNRT,
    navigation: 7EYY4ZMNOEYXYW73BTCH3LRCTFXGCHWX, augment: KLAW5P5PSQCMT6J36KVEC3DK3YAPGF2Q}
  server_modules: {authorisation: D7SRIT2SYQPSIV2AJXWJNZFPWC4WKRHA, server_utils: 2WAPQLVSNVDZP5YEK6U6GAALEF4GCFCA}
  assets: {loading-spinner.js: ZRZS2RFHFQREOOXYLFPIXVN56OL7BJLY, standard-page.html: JYT2VG6NOSSLRNZR5GDSLLXUFJ7AZF4J,
    theme.css: S5NWY72JOUFUHCDRRQX7DV3C5CKF4TGN}
