name: check_codebase

on:
  push:
    branches: [main, feat/radio-group]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint/Docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv and set Python version
      uses: astral-sh/setup-uv@v5
      with:
        python-version: '3.12'
        enable-cache: true
    - name: Install dependencies
      run: |
        uv pip install pre-commit sphinx sphinx_rtd_theme bump2version anvil-uplink marshmallow
    - name: Run pre-commit
      run: |
        uv run pre-commit run --all-files
    - name: Check docs build
      run: |
        uv run sphinx-build docs build
    - name: Check version numbering
      run: |
        uv run bumpversion --dry-run patch

  test:
    name: Tests on Python 3.7
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Debug runner
      run: |
        echo "Runner started"
        uname -a
        python3 --version
    - uses: actions/checkout@v4
    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'
    - name: Verify Python
      run: |
        python --version
        which python
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
    - name: Install test dependencies (3.7-compatible)
      run: |
        uv pip install --system -r requirements.txt "pytest<8"
    - name: Run test suite (3.7)
      run: |
        python -m pytest
