name: check_codebase

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint/Docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv and set Python version
      uses: astral-sh/setup-uv@v5
      with:
        python-version: '3.12'
        enable-cache: true
    - name: Run pre-commit
      uses: pre-commit/action@v3.0.1
      with:
        extra_args: --all-files
    - name: Install dependencies
      run: |
        uv pip install sphinx sphinx_rtd_theme bump2version anvil-uplink marshmallow
    - name: Check docs build
      run: |
        uv run sphinx-build docs build
    - name: Check version numbering
      run: |
        uv run bumpversion --dry-run patch

  test:
    name: Tests on Python 3.7
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Install uv and Python 3.7
      uses: astral-sh/setup-uv@v5
      with:
        python-version: '3.7'
        enable-cache: true
    - name: Install test dependencies (3.7-compatible)
      run: |
        uv pip install -r requirements.txt "pytest<8"
    - name: Run test suite (3.7)
      run: |
        uv run python -m pytest
