name: check_codebase

on:
  push:
  pull_request:

jobs:
  check:
    name: Check code base
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv and set Python version
      uses: astral-sh/setup-uv@v5
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        uv pip install flake8 pytest black isort sphinx sphinx_rtd_theme bump2version anvil-uplink marshmallow
    - name: Lint with flake8
      run: |
        uv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=.venv
        uv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=.venv
    - name: Check format with black
      run: |
        uv run black --check . --exclude=.venv
    - name: Check imports with isort
      run: |
        uv run isort --check-only client_code
        uv run isort --check-only server_code
    - name: Run test suite
      run: |
        uv run -m pytest
    - name: Check docs build
      run: |
        uv run sphinx-build docs build
    - name: Check version numbering
      run: |
        uv run bumpversion --dry-run patch
